### ISSUE TITLE
Add hyperlinks to wikipedia to the related topics in readme.md

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Data-Science-Algorithms#8]
I would like to add hyperlinks to all the related topics in Wikipedia to the algorithms mentioned in the readme.md file

**Describe the solution you'd like**
I would just like hyperlinks and possible reformatting of the readme.md file to look a bit better, shouldn't be too difficult.

**Additional context**
Since this is an educational resource having links for more information on these topics would serve as a helpful educational aid.

**Comment by rcallaby** [comment]
Please be sure to comment here before taking this on, so I can assign it to you.

**Comment by MichalPKN** [comment]
Hello, I can take this on

**Comment by rcallaby** [comment]
Absolutely!

**Comment by rcallaby** [comment]
Great job on this!
